# Interesting Numpy Functions


### Here are a few examples of useful numpy functions

Write a short introduction about Numpy and list the chosen functions. 

- np.extract
- np.reshape
- np.transpose
- np.copyto
- np.hstack

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

<IPython.core.display.Javascript object>

In [5]:
jovian.commit(filename='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.ai/andrewkamaukim/numpy-array-operations


'https://jovian.ai/andrewkamaukim/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.extract  # (change this)
function2 = np.reshape
function3 = np.transpose
function4 = np.copyto
function5 = np.hstack

## Function 1 - np.extract

This function can be used to extract values from an array based on a certain condition.

In [19]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

arr3=np.concatenate(np.concatenate((arr1, arr2),axis=1))
condition= np.mod(arr3,2)==0
np.extract(condition,arr3)

array([ 2.,  6.,  4.,  8., 10.])

The above example shows the working of np.extract, and the numbers divisible by 2 in the final array, arr3. The condition passed is where the modulus of numbers in arr3 is 0.

In [20]:
# Example 2 - working
condition=np.mod(arr2,3)==0
np.extract(condition,arr2)

array([6, 9])

In the second example, we use array 2, and a condition where the numbers are divisible by 3. 

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
condition=np.mod(arr1,2)==0
np.extract(arr1)

TypeError: _extract_dispatcher() missing 1 required positional argument: 'arr'

The above example fails because a conditional argument is required. This maybe avoided by passing only one argument, the condition, or two, the condition and the array.

In [34]:
condition=np.mod(arr1,2)==0
np.concatenate(arr1)[np.concatenate(condition)]

array([2., 4.])

This function is useful when trying to find values in an array that meet certain conditions.

In [36]:
jovian.commit(filename="numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "andrewkamaukim/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/andrewkamaukim/numpy-array-operations


'https://jovian.ai/andrewkamaukim/numpy-array-operations'

## Function 2- reshape

This gives an array a new shape that we desire

In [10]:
# Example 1 - working
arr1= np.arange(1,60,3)
print(np.size(arr1))
print(arr1.reshape(4,5))

20
[[ 1  4  7 10 13]
 [16 19 22 25 28]
 [31 34 37 40 43]
 [46 49 52 55 58]]


The above example takes an array of size 20, and creates a new shape for it, with 4 rows and 5 columns.

In [11]:
# Example 2 - working
print(arr1.reshape(2,5,2))

[[[ 1  4]
  [ 7 10]
  [13 16]
  [19 22]
  [25 28]]

 [[31 34]
  [37 40]
  [43 46]
  [49 52]
  [55 58]]]


The above example takes the same arrar with size 20, and creates 2 arrays, each with size 5,2, based on the passed arguments; 2, 5 and 2.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
print(arr1.reshape(3,2))

ValueError: cannot reshape array of size 20 into shape (3,2)

Now, since the array is of size 20, we cannot reshape it to a shape of 3,2. This is because the numbers are not compatible divisible. Therefore, when using reshape, we have to use numbers that are compatible with the size of the array. In this case, divisible by 20.

This function is useful when working with arrays of different sizes, and in order to make them compatible, we might need to reshape them.

In [38]:
jovian.commit(filename="numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "andrewkamaukim/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/andrewkamaukim/numpy-array-operations


'https://jovian.ai/andrewkamaukim/numpy-array-operations'

## Function 3- np.transpose

This function returns an array with transposed arrays

In [47]:
# Example 1 - working
arr1=np.array([[1,2],[3,4]])
print(arr1)
np.transpose(arr1)

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

The above example shows an array 

In [48]:
# Example 2 - working
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
np.transpose(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Explanation about example

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
a='high'
np.transpose(float(a))

ValueError: could not convert string to float: 'high'

The transpose function will rarely break as it will transpose any object passed to it by first turning into an array. In the above case, the error is brought about by trying to turn a word to a float, which causes a valueerror.

This function may be used to perform iear algebra transposition operations.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4- Copyto

`copyto` copies values from one array to another

In [73]:
# Example 1 - working
a=np.arange(6)
b=np.ones(6)
print(b)
np.copyto(b,a)
print('b:', b)

[1. 1. 1. 1. 1. 1.]
b: [0. 1. 2. 3. 4. 5.]


The above example copies values from a to b

In [75]:
# Example 2 - working
a=np.array([[1,2],[3,4]])
b=[[9,10],[11,12]]
np.copyto(a,b)
a

array([[ 9, 10],
       [11, 12]])

The example copies values of b to a

In [78]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.arange(10)
b=np.arange(5)
np.copyto(a,b)

ValueError: could not broadcast input array from shape (5,) into shape (10,)

The above breaks because the two arrays being copied to one another are not of the same shape.

You can use copyto when you have multiple similar arrays in shape and would like the values in some to be copied to the others

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5- hstack

This stacks arrays in sequence horizontally

In [84]:
# Example 1 - working
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

The function takes the two arrays a and b, and returns an array with all their elements

In [88]:
# Example 2 - working
a=np.array([[5],[6],[7]])
b=np.array([[6],[7],[9]])
np.hstack((a,b))

array([[5, 6],
       [6, 7],
       [7, 9]])

The above example takes each element in each array, and stacks it alongside the coinciding element.

In [89]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack(a,b)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

The two arrays have to be given as one, by joining as a tuple.

This function is useful when you want to join multiple arrays in a horizontal manner

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

In this notebook, we covered multiple numpy functions.
1. extract
2. reshape
3. transpose
4. copyto
5. hstack

The way to go after this is practice, practice, practice..

## Reference Links
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Medium article: https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8

In [91]:
jovian.commit(filename="numpy-array-operations.ipynb")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "andrewkamaukim/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/andrewkamaukim/numpy-array-operations


'https://jovian.ai/andrewkamaukim/numpy-array-operations'